### ISSUE TITLE
Cscope DB not connected automatically

### ISSUE THREAD

**Issue by j5shi** [brookhong/cscope.vim#10]
>  ID                   LOADTIMES    PATH
    \*1337668712           3            /works/vim/src
    '*'         means the db has been connected.
    ID          id of the db.
    LOADTIMES   how many times this db has ever been used.
    PATH        which folder the db is for.

I can see cscope db within ` :CscopeList`, however, the DB was not connected, i.e. `\*` not appeared and db not seen in `:cs show`.

**Comment by brookhong** [comment]
The DB will be connected only after CscopeFind or CscopeFindInteractive called, which means you must press at least one of the mapping keys like `<leader>fa` or `<leader>fs`.
