### ISSUE TITLE
Define File Types to Generate Cscope DB

### ISSUE THREAD

**Issue by j5shi** [brookhong/cscope.vim#11]
Would be nice to add interface to define file types, e.g. `.c,.h,.cpp...` to generate cscope DB.

**Comment by brookhong** [comment]
*'g:cscope_interested_files'*
Specify the extentions you want to include when building cscope database, the
default extentions are listed in interested.txt.
  let g:cscope_interested_files = '\.c$\|\.cpp$\|\.h$\|\.hpp'

**Comment by j5shi** [comment]
Good, thanks!

Sent from my Windows Phone
________________________________
发件人: brookhong<mailto:notifications@github.com>
发送时间: ‎2015/‎5/‎15 22:59
收件人: brookhong/cscope.vim<mailto:cscope.vim@noreply.github.com>
抄送: Jia<mailto:j5shi@live.com>
主题: Re: [cscope.vim] Define File Types to Generate Cscope DB (#11)

Closed #11.

---
Reply to this email directly or view it on GitHub:
https://github.com/brookhong/cscope.vim/issues/11#event-305914981
