### ISSUE TITLE
Cscope update database too often

### ISSUE THREAD

**Issue by j5shi** [brookhong/cscope.vim#14]
It takes a lot of time in updating database as it updates too often. I want it to update automatically, but more silently, better to support asynchronous update.

**Comment by brookhong** [comment]
*'g:cscope_split_threshold'*
Specify a number. If total files found for a directory exceeds it, then a
separate cscope database will be created for modified/added files to avoid
long time for updating cscope database.
  let g:cscope_split_threshold = 9999

**Comment by j5shi** [comment]
I will try it for a while and then decide if this issue could be closed, thanks for your feedback.

**Comment by j5shi** [comment]
There's still room for improvement for this solution.
