### ISSUE TITLE
cscope.vim vs cscope_maps.vim?

### ISSUE THREAD

**Issue by githubfun** [brookhong/cscope.vim#23]
any reasons I better use cscope.vim instead of http://cscope.sourceforge.net/cscope_maps.vim?

Thanks!

**Comment by brookhong** [comment]
cscope.vim is not to provide key mappings, it's to help to create/update cscope database and connect to existing proper database automatically.

**Comment by githubfun** [comment]
I removed 

`if has("cscope")
    if filereadable("cscope.out")
        cs add cscope.out
    endif
endif
`
from my vimrc, otherwise I got error. Thaks for this plugin!
