### ISSUE TITLE
Going back from a cscope jump

### ISSUE THREAD

**Issue by drozdziak1** [brookhong/cscope.vim#24]
I think it would be awesome for your already great plugin to support a stack of a buffer's last visited files, just like ctags lets you come back from a jump with Ctrl + T

**Comment by brookhong** [comment]
It seems not a feature related with cscope -- this plugin.

Does ctrl-i /ctrl-o help your case? If it does not, you may try `:CtrlPBuffer` from https://github.com/ctrlpvim/ctrlp.vim.

**Comment by drozdziak1** [comment]
Yup, ctrl-o works like a charm, should've done more homework on vim
