### ISSUE TITLE
How to exclude directories

### ISSUE THREAD

**Issue by networklearners** [brookhong/cscope.vim#25]
Hi,

Can we get fix to exclude directories from the project ?
I do not want to include files which are part of specific directories under the project directories

**Comment by brookhong** [comment]
Fixed with commit https://github.com/brookhong/cscope.vim/commit/a9942da694e92dc938ad8d6c06a823c2434a47ea

Specify the sub directories you want to exclude when building cscope database, for
example:

```
let g:cscope_ignored_dir = 'node_modules$\|dist$'
```

**Comment by c02y** [comment]
It seems it doesn't work.

I'm using 
~~~
let g:cscope_ignored_dir = '.ccls-cache$\|test$'
~~~
or
~~~
let g:cscope_ignored_dir = '.ccls-cache'
~~~

and when I open a cpp file, and use cscope function, it still displays the result from .ccls-cache directory.
and `:let g:cscope_ignored_dir` is the variable I set.
