### ISSUE TITLE
Is there any history lost from vim.org days?

### ISSUE THREAD

**Issue by albfan** [brookhong/cscope.vim#26]
Why not rebase this upon vim-scripts to preserve history from previous releases?

**Comment by wsdjeg** [comment]
emm, I want to for this plugin to SpaceVim org. and to let more people maintain it. I use your fork ag.vim. it is nice, but can I use rg instead of ag.

**Comment by wsdjeg** [comment]
and why I want to fork?

I think this plugin should use autoload feature. less scripts in plugin/ will make vim startup more fast.

**Comment by albfan** [comment]
Opps sorry, I was trying several cscope plugins and and paste wrong one. I mean rebase on top of https://github.com/vim-scripts/cscope.vim, which seems to be yours too.

About spacevim that sounds great, It can be useful for ag.vim too (I was time looking for that for long time)

https://github.com/albfan/ag.vim/issues/97

About rg it should be easy to support:
https://github.com/albfan/ag.vim/issues/98

Feel free to open more issues on ag.vim

I want to tweak cscope.vim a little, so If you open issues here about your ideas, maybe we can collaborate to implement it

**Comment by brookhong** [comment]
You guys are genius. 🤣 

You are talking A under B, and referring C, then D.  Looks like nothing I can do here.  Feel free to fork whatever you mean. I'm closing it.

**Comment by wsdjeg** [comment]
@brookhong sorry I mean I want to fork this, and make some change to open a PR. now the plugin is under dir `plugin/`, all script will be load when vim startup, I think it will make vim startup slow, can you use autoload feature?

**Comment by albfan** [comment]
Opps. I though I was talking to you @brookhong. It sound to me too extrange to me too

**Comment by albfan** [comment]
@brookhong better this way?

**Comment by albfan** [comment]
@wsdjeg that's not relevant to this issue, is another issue you should open. @brookhong why not rebase on top of vim-scripts to preserve you commits before github repo?

**Comment by brookhong** [comment]
@albfan 
Actually this repo has more commits than the one from vim-scripts, we need not do that.

I maintain the plugin here in this repo, and released them onto vim.org years ago. And the account vim-scripts is an automated one, which automatically uploads all plugins uploaded to vim.org to github.

I stopped to upload plugin to vim.org since I found that using [vundle](https://github.com/VundleVim/Vundle.vim) to manage plugin is such a pleasure.

Same story for vundle, you need not ask maintainer of https://github.com/VundleVim/Vundle.vim to rebase on https://github.com/vim-scripts/vundle.

**Comment by brookhong** [comment]
@wsdjeg 

Thanks for suggestion.
I'll see if there is any chance to modify it into autoload mode.

**Comment by wsdjeg** [comment]
Thanks  I will add this plugin to SpaceVim's tools layer.

**Comment by albfan** [comment]
@brookhong I see now issue tittle was wrong. Just want to ask: Is there any history lost from vim.org days? Answer is no, so there's no need to rebase or whatever.

Great, let's start to hack on it then

**Comment by brookhong** [comment]
nope, this repo is having the full commits.
