### ISSUE TITLE
Is it possible to support update cscope db file incrementally?

### ISSUE THREAD

**Issue by liming01** [brookhong/cscope.vim#8]
Now it just overwrite each time when running CscopeGen. However, the cscope commmand already support incremental update, why do we need to overwrite it? Thanks.

**Comment by liming01** [comment]
Find a related plugin: vim-scripts/cscope_dynamic for dynamic update cscope db files, however there is no simple ways to auto detect the path for the generated db.

**Comment by brookhong** [comment]
Thanks for feedback.
The feature is implemented in my way, please check out the latest version and have a try.

Please take a look at the doc and screencast for usage, as some functions/settings are changed.

**Comment by parihartarun** [comment]
i work on large codebase and automatic updates are just freezing vim for 2 to 3 minutes. Do you have any plan to enhance this plugin in near future. Is there any mechanism to exclude some directories from cscope database?
