### ISSUE TITLE
Configure option to add only allowed filetypes.

### ISSUE THREAD

**Issue by mulianov** [brookhong/cscope.vim#9]
I think sometimes its better to configure filetypes you want to add to DB (e.g. *.c *.h) and ignore all other. In big projects there is a loooot different filetypes...

**Comment by brookhong** [comment]
Specify the extentions you want to include when building cscope database, the
default extentions are listed in interested.txt.

    let g:cscope_interested_files = '\.c$\|\.cpp$\|\.h$\|\.hpp'

**Comment by mulianov** [comment]
Ooops ) Sorry, i missed latest changes in repo. Thx!
